name: Publish Gem

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to RubyGems
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
        
    - name: Build gem
      run: gem build env_check.gemspec
      
    - name: Publish to RubyGems
      run: |
        mkdir -p ~/.gem
        cat << EOF > ~/.gem/credentials
        ---
        :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
        EOF
        chmod 600 ~/.gem/credentials
        gem push *.gem
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
